---
abstract: 'Minimum and maximum values allowed by an inequality.'
author:
  - 'Tomas Doran (t0m) C<< <bobtfish@bobtfish.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Inequalities-Parser
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bobtfish/Math-Inequalities-Parser.git
version: 0.002
